name: CI Basic Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run application check script
        run: |
          chmod +x ./gtacd/app/check_app.sh
          chmod +x ./gtacd/app/var.sh
          ./gtacd/app/check_app.sh

      - name: Display index.html content
        run: cat ./gtacd/app/index.html
